<template>
<div class="widget-container" 
  :class="{
    'editable': editable,
    'selected-widget': selected_widget == index
  }"
  v-if="widget"
  :style="{
    'margin-top': (widget.top || 0) + 'px',
    'margin-bottom': (widget.bottom || 0) + 'px',
  }"
  @click="select_widget(index)"
>



    <!--                                    -->
    <!-- Widget options, generated by v-for -->
    <!--                                    -->

    <!-- Utility (will not show up when the page is viewed )-->

    <new-widget v-if="widget.type == 'new'"
      :value="widget" 
      @input="emit_update($event.path, index, $event.new_val)">
    </new-widget>


    <!-- Decorative -->

    <line-break v-if="widget.type == 'line-break'" color="var(--bg-text2)"></line-break>
    

    <!-- Text -->

    <page-header v-if="widget.type == 'header'" 
      :editable="editable"
      :value="widget" 
      @input="emit_update($event.path, index, $event.new_val)">
    </page-header>

    <page-subheader v-if="widget.type == 'subheader'" 
      :editable="editable"
      :value="widget" 
      @input="emit_update($event.path, index, $event.new_val)">
    </page-subheader>

    <!-- Tabs: -->
    <div class="tab-container" v-else-if="widget.type == 'tabs'">
      <div class="tabs" >
        <text-field class="tab" 
          v-for="(tab, tabindex) in widget.tabs" 
          :class="{ 'bold': widget.selectedTab == tabindex}" 
          nobox 
          @click="widget.selectedTab = tabindex" 
          v-model="tab.name" 
          :key="'tab-' + tabindex">
        </text-field>
        <div class="tab add-tab" @click="addTab(widget)">+ Add Tab</div>
      </div>
    </div>

    <!-- section title: -->
    <section-title v-else-if="widget.type == 'section-title'" 
      :editable="editable"
      :value="widget" 
      @input="update_data(index, $event)">
    </section-title>

    <!-- subsection title: -->
    <subsection-title v-else-if="widget.type == 'subsection-title'" 
      :editable="editable"
      :value="widget" 
      @input="update_data(index, $event)">
    </subsection-title>
    
    <!-- Paragraphs: -->
    <paragraph v-else-if="widget.type == 'paragraph'" 
      :editable="editable"
      :value="widget" 
      @input="emit_update($event.path, index, $event.new_val)">
    </paragraph>

    <article-card v-else-if="widget.type == 'article'" :editable="editable"
    :owner="owner"
    :value="widget" @input="update_data(index, $event)">
    </article-card>

    <collection v-else-if="widget.type == 'collection'" :editable="editable"
    :owner="owner"
    :value="widget" @input="emit_update($event.path, index, $event.new_val)">
    </collection>

    <!-- Images: -->
    <!--
    <div class="image-section" v-else-if="widget.type == 'image'" @change="uploadFile($event, index)" enctype="multipart/form-data"
          @click="openSVGInput(index)">
        
      <input type="file" accept="image/svg" ref="fileInput" style="display: none;">
      <p v-if="!widget.content">+ Upload an Image</p>
      <div v-html="widget.content" v-else></div>

    </div>-->
    
    <div class="image-section" v-else-if="widget.type == 'image'">
      <svg-uploader v-model="widget.content" :ref="'svg_uploader_'"></svg-uploader>
    </div>
</div>
</template>

<script>


// Widgets:
import newWidget from '@/components/widgets/new_widget.vue';

// Text widgets:
import pageHeader from '@/components/widgets/text/page_header.vue';
import pageSubheader from '@/components/widgets/text/page_subheader.vue';

import sectionTitle from '@/components/widgets/text/section_title.vue';
import subsectionTitle from '@/components/widgets/text/subsection_title.vue';
import paragraph from '@/components/widgets/text/paragraph.vue';

export default {
  name: 'widget-renderer',
  components: {
    pageHeader,
    pageSubheader,

    sectionTitle,
    subsectionTitle,
    paragraph,
    newWidget
  },

  props: {
    // Who owns this doc?
    owner: {
      type: String,
    },
    // editable content? 
    editable: {
      type: Boolean,
      default: false,
    },
    // Toggles visual boxes around inputs
    noboxes: {
      type: Boolean,
      default: true
    },
    index: Number,
  },

  computed: {

    widget() {
      return this.$store.getters['page/body_widget'](this.index);
    },

    // We don't display the "add section" button if this page is a parent,
    // because the add section button will go in the child element:
    isParent() { 
      for (let i in this.data) {
        if (this.data[i].type == 'tabs') {
          return true;
        }
      }
      return false;
    }
  },

  data() {
    return {

      selected_widget: -1, // the widget clicked on last
      editElement: -1, // This indicates the index of the element being edited
      
    }
  },


  methods: {
    // When the user clicks on a widget
    select_widget(index) {
      this.selected_widget = index;
      this.$emit('widgetselect', index);
    },


    update_data(field, new_val) {
      let update = JSON.parse(JSON.stringify(this.widget));
      
      this.$store.commit('pages/load_body_widget', {
        index: this.index,
        widget: update
      });
      let data_update = JSON.parse(JSON.stringify(this.value));
      data_update[field] = new_val;
      this.$emit('input', data_update);
    },

    // new update func:
    emit_update(path, new_index, new_val) {
      let new_path = path;
      new_path.unshift(new_index);
      this.$emit('input', {
        path: new_path,
        new_val: new_val,
      });
    },

    // Clicking on the gear icon:
    editSelect(i) {
      if (this.editElement == i) {
        this.editElement = -1;
      } else {
        this.editElement = i;
      }
    },

    add_widget() {
      this.data.push({
        type: 'new',
        content: ''
      });
      this.editElement = this.data.length - 1;
      // updates the data reactivity
      this.$forceUpdate(); //todo: is this too hacky?
    },

    // Called when a file is uploaded
    uploadFile(event, elementIndex) {
      let _file = event.target.files[0];
      console.log(_file);
      let fileName = _file.name;
      // Reading the file's contents
      this.readFileContent(_file).then(fileContent => {
        this.data[elementIndex].content = fileContent;
      }).catch(error => console.log(error))

    },

    // This function takes an svg file and returns the actual XML code of that SVG as a string.
    // It uses FileReader, a web API available by default in modern browsers.
    readFileContent(file) {
      const reader = new FileReader()
      // We're returning a promise, which  means you can use the .then(() => {}) function on this one!
      return new Promise((resolve, reject) => {
        reader.onload = event => resolve(event.target.result)
        reader.onerror = error => reject(error)
        reader.readAsText(file)
      })
    },

    // Clicks on the hidden input so we can use our custom-styled input
    openSVGInput() {
      this.$refs['fileInput'][0].click()
    },

    // Adds a tab section
    addTab(tabElement) {
      
      tabElement.tabs.push({
        "name": "New Tab",
        "content": [
            {
                "type": "section-title",
                "content": ""
            },
            {
                "type": "subsection-title",
                "index": "1.1",
                "content": ""
            },
            {
                "type": "paragraph",
                "content": ""
            }
        ]
      });
    }

  },

  

}
</script>

<style lang="scss" scoped>
// Note that this style isn't scoped, since it needs to reach inside components?

// Content contains all the inputs:
.body {
  width: 100%;
  max-width: 600px;
  align-content:flex-start;
}

// The v-for generated widget containers
.widget-container {
  position: relative;
  transition-duration: .2s;
  margin-bottom: 5px;
}

// The two selection light indicators to the sides of widgets. 
// Styling:
.widget-container.editable::before, .widget-container.editable::after {
  content: '';
  height: 15px;
  width: 15px;
  top: calc(50% - 7px);
  border: solid 5px var(--bg); // invisible border makes it appear small, but be easy to grab
  border-radius: 50%;
  position: absolute;
  cursor: grab;
  transition-duration: .4s;
  background: var(--card);
}
.widget-container.selected-widget::after, .widget-container.selected-widget::before {
  background: var(--c1);
}
// Positions:
.widget-container.editable::before {
  left: -20px;
}
.widget-container.editable::after {
  right: -20px;
}




.tab-container {

}
.tabs {
  display: flex;
  margin-top: 50px;
  border-bottom: solid 2px var(--bg-text2);
  margin-bottom: 20px;

  .tab {
    font-size: var(--small-font-size);
    width: 150px;
    padding: 0px;
    text-align: center;
    position: relative;
    cursor: pointer;
    margin-top: -2px;
    transform: translatey(2px); // This offset lets the border-bottoms line up
    input {
      text-align: center;
      padding: 10px 0px;
      margin: 0px;
    }
  }
  .add-tab {
    color: var(--bg-text2);
    font-size: var(--small-font-size);
    &:hover {
      
      color: var(--bg-text);
    }
  }
}
.tab-content {

}




// For sections containing images:
.image-section {
  cursor: pointer;
  width: 100%;
  min-height: 100px;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: space-around;
  padding: 10px;
  p {
    cursor: pointer;
  }
  &:hover {
    background: var(--input);
  }
  .image-uploader {
    width: 100%;
    height: 100%;
  }
}

// Add section button:
#add-section-button {
  margin-top: 20px;
  width: 100%;
  padding: 10px;
}

input:active, input:hover {
  background: var(--input);
}
</style>